spring:
  application:
    name: spring-boot-admin-istio


spring.boot.admin.discovery:
  ignored-services:
    - spring-boot-admin-istio
    - kubernetes

spring.cloud.kubernetes.discovery.



logging:
  level:
    de.codecentric.boot.admin.server: debug