---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-admin-client
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-boot-admin-client
  template:
    metadata:
      labels:
        app: spring-boot-admin-client
    spec:
      containers:
        - name: app
          image: altfatterz/spring-boot-admin-client:1.0.0
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            timeoutSeconds: 1
            periodSeconds: 10
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 120
---

apiVersion: v1
kind: Service
metadata:
  name: spring-boot-admin-client
spec:
  selector:
    app: spring-boot-admin-client
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
