---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hazelcast-embedded
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hazelcast-embedded
  template:
    metadata:
      labels:
        app: hazelcast-embedded
    spec:
      containers:
        - name: hazelcast-embedded
          image: altfatterz/hazelcast-embedded:1.0.0
          ports:
            - containerPort: 5701
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name

---

apiVersion: v1
kind: Service
metadata:
  name: hazelcast-embedded-headless
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: hazelcast-embedded
  ports:
    - name: tcp-hazelcast
      port: 5701

---

apiVersion: v1
kind: Service
metadata:
  name: hazelcast-embedded
spec:
  type: ClusterIP
  selector:
    app: hazelcast-embedded
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
